<a href="https://colab.research.google.com/github/NityaVerma19/Customer-Purchase-Decision-/blob/master/Consumer_behaviour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split


#Generating a dataset

### Product Info

In [ ]:
#green packaging

def generate_random_series(length, seed=1):
    random.seed(seed)
    return [random.choice([0, 1]) for _ in range(length)]

def add_binary_noise(series, noise_prob=0.55, seed=None):
    if seed is not None:
        random.seed(seed)
    noisy_series = []
    for value in series:
        if random.random() < noise_prob:
            noisy_series.append(1 - value)  # Flip the value with probability noise_prob
        else:
            noisy_series.append(value)
    return noisy_series

length = 3000
green_pack = generate_random_series(length, seed=43)

noisy_green_pack = add_binary_noise(green_pack, noise_prob=1, seed=1)

In [ ]:
#purchase decision - yes/no

def generate_random_series(length, seed = 2):
    random.seed(seed
    )
    return [random.choice([0, 1]) for _ in range(length)]

def add_noise(series, noise_prob=0.35, seed=None):
    if seed is not None:
        random.seed(seed)
    noisy_series = []
    for value in series:
        if random.random() < noise_prob:
            noisy_series.append(1 - value)  # Flip the value with probability noise_prob
        else:
            noisy_series.append(value)
    return noisy_series

length = 3000
purchase = generate_random_series(length, seed=2)

noisy_purchase = add_binary_noise(green_pack, noise_prob=1, seed=5)


In [ ]:
#type of product - 'Beverage', 'Food' , 'Beauty', 'Personal hygiene', 'Paper products' , 'Clothing'


def generate_random_series(words, length, seed = 42):
    random.seed(seed)
    series = [random.choice(words) for _ in range(length)]
    return series

word_list = ['Beverage', 'Food' , 'Beauty', 'Personal hygiene', 'Paper products' , 'Clothing']
series_length = 3000

product = generate_random_series(word_list, series_length, seed = 42)


In [ ]:
import numpy as np
import pandas as pd
import random

def generate_random_series(lower_bound, upper_bound, count, seed=42):
    random.seed(seed)
    random_numbers = np.random.randint(lower_bound, upper_bound + 1, count)
    return pd.Series(random_numbers)

#for adding noise to the dataset so that it becomes more authentic
def add_multiplicative_noise(series, noise_scale= 2, seed=None):
    if seed is not None:
        random.seed(seed)
    noise_factors = np.random.normal(loc=1.0, scale=noise_scale, size=len(series))
    return series * noise_factors

lower_bound = 500
upper_bound = 5000
count = 3000

price = generate_random_series(lower_bound, upper_bound, count, seed=42)

noisy_price = add_multiplicative_noise(price, noise_scale=0.05, seed=42)

# Ensure that the resulting prices remain positive
noisy_price = noisy_price.clip(lower=lower_bound)  # Clip to ensure prices don't go below lower_bound

### Customer Info

In [ ]:
#Age

import numpy as np
import pandas as pd
import random

def generate_random_series(lower_bound, upper_bound, count, seed=42):
    random.seed(seed)
    random_numbers = np.random.randint(lower_bound, upper_bound + 1, count)
    return pd.Series(random_numbers)

def add_discrete_noise(series, noise_scale=3, seed=None):
    if seed is not None:
        random.seed(seed)
    noise = np.random.randint(-noise_scale, noise_scale + 1, len(series))
    noisy_series = series + noise
    noisy_series = np.clip(noisy_series, lower_bound, upper_bound)
    return pd.Series(noisy_series)

lower_bound = 18
upper_bound = 50
count = 3000


age = generate_random_series(lower_bound, upper_bound, count, seed=42)

noisy_age = add_discrete_noise(age, noise_scale=2, seed=42)

In [ ]:
#Gender


def generate_random_series(words, length, seed = 42):
    random.seed(seed)
    series = [random.choice(words) for _ in range(length)]
    return series

word_list = ['M', 'F']
series_length = 3000

gender = generate_random_series(word_list, series_length, seed = 42)


In [ ]:
#income = 15k to 150k

def generate_random_series(lower_bound, upper_bound, count, seed=42):
    random.seed(seed)
    random_numbers = np.random.randint(lower_bound, upper_bound + 1, count)
    return pd.Series(random_numbers)

def add_multiplicative_noise(series, noise_scale=2.5, seed=None):
    if seed is not None:
        random.seed(seed)
    noise_factors = np.random.normal(loc=1.0, scale=noise_scale, size=len(series))
    return series * noise_factors

lower_bound = 15000
upper_bound = 150000
count = 3000

income = generate_random_series(lower_bound, upper_bound, count, seed=42)
noisy_income = add_multiplicative_noise(income, noise_scale=0.05, seed=42)

noisy_income = np.round(noisy_income / 10) * 10

In [ ]:
#customer id
numbers_sequence = range(1, 3000)
cust_id = pd.Series(numbers_sequence)


*Merging the series*

In [ ]:
df = pd.DataFrame({'cust_id': cust_id,'product': product, 'price': noisy_price, 'green_pack': noisy_green_pack, 'age': noisy_age,'gender': gender, 'income': noisy_income, 'purchase': noisy_purchase })
df.head()

cust_id   product        price  green_pack  age gender   income  purchase
0      1.0  Clothing  2743.044244           1   38      M  20040.0         1
1      2.0  Beverage  5045.539977           0   43      M  98080.0         0
2      3.0  Beverage  1144.628742           1   34      F  99620.0         1
3      4.0  Clothing  1297.765792           0   23      M  61460.0         0
4      5.0    Beauty   500.000000           0   30      M  25440.0         0

In [ ]:
# Downloading the dataframe

#df.to_csv('df.csv', index=False)

In [ ]:
df.head()

cust_id   product        price  green_pack  age gender   income  purchase
0      1.0  Clothing  2743.044244           1   38      M  20040.0         1
1      2.0  Beverage  5045.539977           0   43      M  98080.0         0
2      3.0  Beverage  1144.628742           1   34      F  99620.0         1
3      4.0  Clothing  1297.765792           0   23      M  61460.0         0
4      5.0    Beauty   500.000000           0   30      M  25440.0         0

In [ ]:
df.shape

(3000, 8)


---





# Logistic Regression


In [ ]:
df.head()

cust_id   product        price  green_pack  age gender   income  purchase
0      1.0  Clothing  2743.044244           1   38      M  20040.0         1
1      2.0  Beverage  5045.539977           0   43      M  98080.0         0
2      3.0  Beverage  1144.628742           1   34      F  99620.0         1
3      4.0  Clothing  1297.765792           0   23      M  61460.0         0
4      5.0    Beauty   500.000000           0   30      M  25440.0         0

In [ ]:
#feature variable

X = df.drop(columns = ['cust_id', 'purchase'], axis= 1)


#target variable

y = df.purchase.values



In [ ]:
#splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [ ]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((2400, 6), (600, 6))

*Feature engineering*

In [ ]:
# display categorical variables

categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']

categorical

['product', 'gender']

In [ ]:
#display numerical variables

numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']

numerical

['price', 'green_pack', 'age', 'income']

In [ ]:
X_train.describe()

price   green_pack          age         income
count  2400.000000  2400.000000  2400.000000    2400.000000
mean   2723.329384     0.492083    33.917083   83093.975000
std    1298.795045     0.500042     9.666867   39049.938422
min     500.000000     0.000000    18.000000   13930.000000
25%    1605.670603     0.000000    26.000000   49795.000000
50%    2730.455192     0.000000    34.000000   83300.000000
75%    3827.170537     1.000000    42.000000  116345.000000
max    5461.716037     1.000000    50.000000  162620.000000

In [ ]:
cols = X_train.columns
cols

Index(['product', 'price', 'green_pack', 'age', 'gender', 'income'], dtype='object')

In [ ]:
pip install category_encoders

*Endoding categorical variable*

In [ ]:
import category_encoders as ce

encoder = ce.BinaryEncoder(cols=['product', 'gender'])

X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [ ]:
X_train.head()

product_0  product_1  product_2        price  green_pack  age  gender_0  \
2370          0          0          1  2208.567334           0   44         0   
1774          0          1          0  3239.276152           1   19         1   
731           0          1          1   639.704926           0   33         1   
271           1          0          0   523.681841           1   20         1   
1077          1          0          1  2881.512033           0   33         1   

      gender_1    income  
2370         1   42670.0  
1774         0  154120.0  
731          0   33810.0  
271          0   94760.0  
1077         0   46710.0

In [ ]:
X_train = pd.concat([X_train[numerical], X_train[['product_0', 'product_1', 'product_2', 'gender_0', 'gender_1']]], axis=1)

X_train.head()


price  green_pack  age    income  product_0  product_1  product_2  \
2370  2208.567334           0   44   42670.0          0          0          1   
1774  3239.276152           1   19  154120.0          0          1          0   
731    639.704926           0   33   33810.0          0          1          1   
271    523.681841           1   20   94760.0          1          0          0   
1077  2881.512033           0   33   46710.0          1          0          1   

      gender_0  gender_1  
2370         0         1  
1774         1         0  
731          1         0  
271          1         0  
1077         1         0

In [ ]:
X_test = pd.concat([X_test[numerical], X_test[['product_0', 'product_1', 'product_2', 'gender_0', 'gender_1']]], axis=1)

X_test.head()


price  green_pack  age    income  product_0  product_1  product_2  \
311    515.397790           1   36  106240.0          0          1          1   
1025  2604.966750           0   23   29370.0          1          0          0   
1587  3584.706589           1   48   76710.0          0          1          0   
2941  1534.888725           1   25   61490.0          0          0          1   
2980  1929.532148           1   24   49380.0          1          0          0   

      gender_0  gender_1  
311          1         0  
1025         0         1  
1587         0         1  
2941         0         1  
2980         1         0

*Feature Scaling*

In [ ]:
cols = X_train.columns

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [ ]:
X_test = pd.DataFrame(X_test, columns=[cols])

*Model Training*

In [ ]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression


# instantiate the model
logreg = LogisticRegression(C = 0.5, solver='liblinear', random_state=1)


# fit the model
logreg.fit(X_train, y_train)

LogisticRegression(C=0.5, random_state=1, solver='liblinear')

*Predict Results*

In [ ]:
y_pred_test = logreg.predict(X_test)

y_pred_test

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,

In [ ]:
# probability of getting output as 0 - no purchase

logreg.predict_proba(X_test)[:,0]

array([0.01533881, 0.97404025, 0.01403461, 0.00905094, 0.00861443,
       0.02263046, 0.98711797, 0.97397071, 0.98039891, 0.01789354,
       0.01411078, 0.01951693, 0.98500291, 0.00920197, 0.01500054,
       0.9847968 , 0.98610132, 0.01317779, 0.01344746, 0.98054583,
       0.98685415, 0.98612241, 0.98219513, 0.98112957, 0.01156942,
       0.01464838, 0.9803028 , 0.9717885 , 0.01601256, 0.01248711,
       0.0182113 , 0.98690475, 0.01003978, 0.98560751, 0.9907062 ,
       0.98693719, 0.01314384, 0.97488613, 0.97531052, 0.97558376,
       0.01682688, 0.01905736, 0.00984153, 0.01383244, 0.98694223,
       0.01740126, 0.02070859, 0.97412292, 0.97436027, 0.01269034,
       0.98495873, 0.00805323, 0.98765265, 0.9859564 , 0.01391903,
       0.97917079, 0.98535802, 0.98791638, 0.01976383, 0.98361082,
       0.01566007, 0.98579536, 0.98926219, 0.98577345, 0.97793224,
       0.98521661, 0.97876475, 0.98101277, 0.98428908, 0.01369636,
       0.98367182, 0.01070883, 0.97521138, 0.01440563, 0.98708

In [ ]:
# probability of getting output as 1 - purchase

logreg.predict_proba(X_test)[:,1]

array([0.98466119, 0.02595975, 0.98596539, 0.99094906, 0.99138557,
       0.97736954, 0.01288203, 0.02602929, 0.01960109, 0.98210646,
       0.98588922, 0.98048307, 0.01499709, 0.99079803, 0.98499946,
       0.0152032 , 0.01389868, 0.98682221, 0.98655254, 0.01945417,
       0.01314585, 0.01387759, 0.01780487, 0.01887043, 0.98843058,
       0.98535162, 0.0196972 , 0.0282115 , 0.98398744, 0.98751289,
       0.9817887 , 0.01309525, 0.98996022, 0.01439249, 0.0092938 ,
       0.01306281, 0.98685616, 0.02511387, 0.02468948, 0.02441624,
       0.98317312, 0.98094264, 0.99015847, 0.98616756, 0.01305777,
       0.98259874, 0.97929141, 0.02587708, 0.02563973, 0.98730966,
       0.01504127, 0.99194677, 0.01234735, 0.0140436 , 0.98608097,
       0.02082921, 0.01464198, 0.01208362, 0.98023617, 0.01638918,
       0.98433993, 0.01420464, 0.01073781, 0.01422655, 0.02206776,
       0.01478339, 0.02123525, 0.01898723, 0.01571092, 0.98630364,
       0.01632818, 0.98929117, 0.02478862, 0.98559437, 0.01291

### Checking Accuracy

In [ ]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score: 1.0000
